# Split sample into student vs. non-student
df_s <- df[df$student_coded ==1, ]
df_ns <- df[df$student_coded ==0, ]

# Descriptive Stats
cols_of_interest = c("MultipleRace_coded",
                     "Other_coded",
                     "White_coded",
                     "Black_coded",
                     "Asian_coded",
                     "Latino_coded",
                     "is_female",
                     "is_non_binary",
                     "is_male",
                     "age_coded",
                     "education_coded",
                     "student_coded",
                     "sp_freq_coded",
                     "sp_during_both_coded",
                     "sp_during_night_coded",
                     "sp_during_day_coded",
                     "sp_more_from_napping",
                     "sp_more_from_nicotine",
                     "sp_more_from_alc",
                     "sp_more_from_caffetine",
                     "number_of_occupants",
                     "noisy_area_coded",
                     "phone_use_coded",
                     "social_media_use_coded",
                     "tech_before_bed_coded",
                     "SC1",       
                     "SC2",      
                     "SC3",       
                     "SC4",
                     "SC5",      
                     "SC6",       
                     "SC7",
                     "PSQI"
                     )
desc_stats_s <- sapply(df_s[,cols_of_interest], function(x) list(means = mean(x,na.rm=TRUE), medians = median(x,na.rm=TRUE), sds = sd(x,na.rm=TRUE)))
desc_stats <- sapply(df[,cols_of_interest], function(x) list(means = mean(x,na.rm=TRUE), medians = median(x,na.rm=TRUE), sds = sd(x,na.rm=TRUE)))

write.csv(desc_stats_s, file="desc_stats_s.csv")
write.csv(desc_stats, file="desc_stats.csv")

# Plot feature distribution across student and non-student sample
install.packages("hrbrthemes")
library("hrbrthemes")

# SP score
ggplot(df, aes(x = sp_freq_coded)) +
      geom_histogram(aes(color = as.factor(student_coded), fill = as.factor(student_coded)), 
                 position = "identity", bins = 30, alpha = 0.4) +
      scale_color_manual(values = c("#00AFBB", "#E7B800")) +
      scale_fill_manual(values = c("#00AFBB", "#E7B800")) +
      facet_wrap(~as.factor(student_coded))

# Age
ggplot(df, aes(x = age_coded)) +
  geom_histogram(aes(color = as.factor(student_coded), fill = as.factor(student_coded)), 
                 position = "identity", alpha = 0.4) +
  scale_color_manual(values = c("#00AFBB", "#E7B800")) +
  scale_fill_manual(values = c("#00AFBB", "#E7B800")) +
  facet_wrap(~as.factor(student_coded))

# Education
ggplot(df, aes(x = education_coded)) +
  geom_histogram(aes(color = as.factor(student_coded), fill = as.factor(student_coded)), 
                 position = "identity", alpha = 0.4) +
  scale_color_manual(values = c("#00AFBB", "#E7B800")) +
  scale_fill_manual(values = c("#00AFBB", "#E7B800")) +
  facet_wrap(~as.factor(student_coded))

# Number_of_occupants
ggplot(df, aes(x = number_of_occupants)) +
  geom_histogram(aes(color = as.factor(student_coded), fill = as.factor(student_coded)), 
                 position = "identity", alpha = 0.4) +
  scale_color_manual(values = c("#00AFBB", "#E7B800")) +
  scale_fill_manual(values = c("#00AFBB", "#E7B800")) +
  facet_wrap(~as.factor(student_coded))

# PSQI
ggplot(df, aes(x = PSQI)) +
  geom_histogram(aes(color = as.factor(student_coded), fill = as.factor(student_coded)), 
                 position = "identity", alpha = 0.4) +
  scale_color_manual(values = c("#00AFBB", "#E7B800")) +
  scale_fill_manual(values = c("#00AFBB", "#E7B800")) +
  facet_wrap(~as.factor(student_coded))
