# FACTOR ANALYSIS - Student Sample

df_s_factor <- df_s %>%
  select(napping_coded, 
         napping_length_coded, 
         alc_use_coded, 
         alc_per_week, 
         alc_at_once, 
         alc_nights_per_week, 
         caffetine_use_coded, 
         caffetine_per_week, 
         caffetine_per_day, 
         family_members_coded, 
         family_number_coded, 
         nicotine_use_coded, 
         nicotine_per_week, 
         nicotine_per_day
  ) 
fa_s_result <- fa(df_s_factor, nfactors = 5, rotate = "varimax")
print(fa_s_result,digits=2, cutoff=0.3, sort=TRUE)
loads_s <- fa_s_result$loadings
fa.diagram(loads_s)
FactorLoadings_s <- round(loads_s[1:14, ], 3)
write.csv(FactorLoadings_s, file="FacLoads_s.csv")

# Cronbach’s Alpha
f1_s <- df_s[ , c("alc_use_coded", "alc_per_week", "alc_at_once", "alc_nights_per_week")]
f2_s <- df_s[ , c("caffetine_use_coded", "caffetine_per_week", "caffetine_per_day")]
f3_s <- df_s[ , c("nicotine_use_coded", "nicotine_per_week", "nicotine_per_day")]
f4_s <- df_s[ , c("family_members_coded", "family_number_coded")]
f5_s <- df_s[ , c("napping_coded", "napping_length_coded")]

psych::alpha(f1_s, check.keys=TRUE)$total[1]
psych::alpha(f2_s, check.keys=TRUE)$total[1]
psych::alpha(f3_s, check.keys=TRUE)$total[1]
psych::alpha(f4_s, check.keys=TRUE)$total[1]
psych::alpha(f5_s, check.keys=TRUE)$total[1]

# CREATING FACTOR SCORES - Student Sample
fa_scores_s <- predict(fa_s_result, df_s_factor)

# Alcohol Factor 
df_s$alc_factor_FA <- fa_scores_s[,1]
# Caffeine Factor
df_s$caffetine_factor_FA <- fa_scores_s[,2]
# Nicotine Factor
df_s$nicotine_factor_FA <- fa_scores_s[,3]
# Family Factor
df_s$family_factor_FA <- fa_scores_s[,4]
# Napping Factor
df_s$napping_factor_FA <- fa_scores_s[,5]

# Testing Skewness - Student Sample
install.packages("Rfast")
library("Rfast")

factor_cols = c("alc_factor_FA","caffetine_factor_FA","nicotine_factor_FA","family_factor_FA","napping_factor_FA")
colskewness(as.matrix(df_s[,factor_cols]))
colkurtosis(as.matrix(df_s[,factor_cols]))

# FACTOR ANALYSIS - Full Sample

df_factor <- df %>%
  select(napping_coded, 
         napping_length_coded, 
         alc_use_coded, 
         alc_per_week, 
         alc_at_once, 
         alc_nights_per_week, 
         caffetine_use_coded, 
         caffetine_per_week, 
         caffetine_per_day, 
         family_members_coded, 
         family_number_coded, 
         nicotine_use_coded, 
         nicotine_per_week, 
         nicotine_per_day
  ) 
fa_result <- fa(df_factor, nfactors = 5, rotate = "varimax")
print(fa_result,digits=2, cutoff=0.3, sort=TRUE)
loads <- fa_result$loadings
fa.diagram(loads)
FactorLoadings <- round(loads[1:14, ], 3)
write.csv(FactorLoadings, file="FacLoads.csv")

# Cronbach’s Alpha
f1 <- df[ , c("alc_use_coded", "alc_per_week", "alc_at_once", "alc_nights_per_week")]
f2 <- df[ , c("caffetine_use_coded", "caffetine_per_week", "caffetine_per_day")]
f3 <- df[ , c("nicotine_use_coded", "nicotine_per_week", "nicotine_per_day")]
f4 <- df[ , c("family_members_coded", "family_number_coded")]
f5 <- df[ , c("napping_coded", "napping_length_coded")]

psych::alpha(f1, check.keys=TRUE)$total[1]
psych::alpha(f2, check.keys=TRUE)$total[1]
psych::alpha(f3, check.keys=TRUE)$total[1]
psych::alpha(f4, check.keys=TRUE)$total[1]
psych::alpha(f5, check.keys=TRUE)$total[1]

# CREATING FACTOR SCORES - Full Sample
fa_scores <- predict(fa_result, df_factor)

# Alcohol Factor 
df$alc_factor_FA <- fa_scores[,1]
# Caffeine Factor
df$caffetine_factor_FA <- fa_scores[,2]
# Nicotine Factor
df$nicotine_factor_FA <- fa_scores[,3]
# Family Factor
df$family_factor_FA <- fa_scores[,4]
# Napping Factor
df$napping_factor_FA <- fa_scores[,5]

# Testing Skewness - Full Sample
install.packages("Rfast")
library("Rfast")

factor_cols = c("alc_factor_FA","caffetine_factor_FA","nicotine_factor_FA","family_factor_FA","napping_factor_FA")
colskewness(as.matrix(df[,factor_cols]))
colkurtosis(as.matrix(df[,factor_cols]))
