setwd("/Users/karenwang/Documents/Sleep Paralysis")

# Import and clean up redundant rows
df <- read.csv("data_coded.csv", header=TRUE)

# Normalize behavioral scores between 0 and 1
library(caret)
# alcohol
df <- df %>% 
  mutate(alc_per_week_adj = predict(preProcess(as.data.frame(alc_per_week), method=c("range")), as.data.frame(alc_per_week))) 
df <- df %>% 
  mutate(alc_at_once_adj = predict(preProcess(as.data.frame(alc_at_once), method=c("range")), as.data.frame(alc_at_once))) 
df <- df %>% 
  mutate(alc_nights_per_week_adj = predict(preProcess(as.data.frame(alc_nights_per_week), method=c("range")), as.data.frame(alc_nights_per_week))) 
# caffeine
df <- df %>% 
  mutate(caffetine_per_week_adj = predict(preProcess(as.data.frame(caffetine_per_week), method=c("range")), as.data.frame(caffetine_per_week))) 
df <- df %>% 
  mutate(caffetine_per_day_adj = predict(preProcess(as.data.frame(caffetine_per_day), method=c("range")), as.data.frame(caffetine_per_day))) 
# nicotine
df <- df %>% 
  mutate(nicotine_per_week_adj = predict(preProcess(as.data.frame(nicotine_per_week), method=c("range")), as.data.frame(nicotine_per_week))) 
df <- df %>% 
  mutate(nicotine_per_day_adj = predict(preProcess(as.data.frame(nicotine_per_day), method=c("range")), as.data.frame(nicotine_per_day))) 
# family
df <- df %>% 
  mutate(family_number_coded_adj = predict(preProcess(as.data.frame(family_number_coded), method=c("range")), as.data.frame(family_number_coded))) 
# napping
df <- df %>% 
  mutate(napping_coded_adj = predict(preProcess(as.data.frame(napping_coded), method=c("range")), as.data.frame(napping_coded))) 
df <- df %>% 
  mutate(napping_length_coded_adj = predict(preProcess(as.data.frame(napping_length_coded), method=c("range")), as.data.frame(napping_length_coded))) 

# Compute behavioral factor manually
# Alcohol Factor 
df$alc_factor_mean <- rowMeans(df[,c("alc_use_coded", "alc_per_week_adj", "alc_at_once_adj", "alc_nights_per_week_adj")], na.rm = TRUE)
# Caffeine Factor
df$caffetine_factor_mean <- rowMeans(df[,c("caffetine_use_coded", "caffetine_per_week_adj", "caffetine_per_day_adj")], na.rm = TRUE)
# Nicotine Factor
df$nicotine_factor_mean <- rowMeans(df[,c("nicotine_use_coded", "nicotine_per_week_adj", "nicotine_per_day_adj")], na.rm = TRUE)
# Family Factor
df$family_factor_mean <- rowMeans(df[,c("family_members_coded", "family_number_coded_adj")], na.rm = TRUE)
# Napping Factor
df$napping_factor_mean <- rowMeans(df[,c("napping_coded_adj", "napping_length_coded_adj")], na.rm = TRUE)

#install.packages("Rfast")
library("Rfast")
factor_cols = c("alc_factor_mean","caffetine_factor_mean","nicotine_factor_mean","family_factor_mean","napping_factor_mean")
colskewness(as.matrix(df[,factor_cols]))
colkurtosis(as.matrix(df[,factor_cols]))

# Split sample into student vs. non-student
df_s <- df[df$student_coded ==1, ]
df_ns <- df[df$student_coded ==0, ]

# HIERARCHICAL LINEAR REGRESSION
# Check missing values
subset_s = df_s[c("sp_freq_coded",
                  "age_coded",
                  "education_coded",
                  "is_female",
                  "PSQI",
                  "caffetine_factor_mean",
                  "nicotine_factor_mean",
                  "family_factor_mean",
                  "napping_factor_mean",
                  "alc_factor_mean")]

subset_ns = df_ns[c("sp_freq_coded",
                    "age_coded",
                    "education_coded",
                    "is_female",
                    "PSQI",
                    "caffetine_factor_mean",
                    "nicotine_factor_mean",
                    "family_factor_mean",
                    "napping_factor_mean",
                    "alc_factor_mean")]

subset = df[c("sp_freq_coded",
                  "age_coded",
                  "education_coded",
                  "is_female",
                  "PSQI",
                  "caffetine_factor_mean",
                  "nicotine_factor_mean",
                  "family_factor_mean",
                  "napping_factor_mean",
                  "alc_factor_mean")]

df_complete_s <- df_s[complete.cases(subset_s), ]
df_complete_ns <- df_ns[complete.cases(subset_ns), ]
df_complete <- df[complete.cases(subset), ]

# Student Sample
# Building the models
m0 <- lm(sp_freq_coded ~ 1, data = df_complete_s, na.action = NULL)
m1 <- lm(sp_freq_coded ~ age_coded + education_coded + is_female, data = df_complete_s, na.action = NULL)
m2 <- lm(sp_freq_coded ~ age_coded + education_coded + is_female + PSQI, data = df_complete_s, na.action = NULL)
m3 <- lm(sp_freq_coded ~ age_coded + education_coded + is_female + PSQI + caffetine_factor_mean + nicotine_factor_mean + alc_factor_mean + napping_factor_mean + family_factor_mean, data = df_complete_s, na.action = NULL)
# anova comparison
anova(m0)
anova(m0, m1, m2, m3)
anova_results <- anova(m1, m2, m3)
# summary stats
summary(m1)
summary(m2)
summary(m3)

# Non-student Sample
# Building the models
m0 <- lm(sp_freq_coded ~ 1, data = df_complete_ns, na.action = NULL)
m1 <- lm(sp_freq_coded ~ age_coded + education_coded + is_female, data = df_complete_ns, na.action = NULL)
m2 <- lm(sp_freq_coded ~ age_coded + education_coded + is_female + PSQI, data = df_complete_ns, na.action = NULL)
m3 <- lm(sp_freq_coded ~ age_coded + education_coded + is_female + PSQI + caffetine_factor_mean + nicotine_factor_mean + alc_factor_mean + napping_factor_mean + family_factor_mean, data = df_complete_ns, na.action = NULL)
# anova comparison
anova(m0)
anova(m0, m1, m2, m3)
anova_results <- anova(m1, m2, m3)
# summary stats
summary(m1)
summary(m2)
summary(m3)


# HIERARCHICAL LINEAR REGRESSION 2
subset_s2 = df_s[c("sp_freq_coded",
                  "age_coded",
                  "education_coded",
                  "is_female",
                  "SC1",
                  "SC2",
                  "SC3",
                  "SC4",
                  "SC5",
                  "SC6",
                  "SC7",
                  "caffetine_factor_mean",
                  "nicotine_factor_mean",
                  "family_factor_mean",
                  "napping_factor_mean",
                  "alc_factor_mean")]

subset_ns2 = df_ns[c("sp_freq_coded",
                    "age_coded",
                    "education_coded",
                    "is_female",
                    "SC1",
                    "SC2",
                    "SC3",
                    "SC4",
                    "SC5",
                    "SC6",
                    "SC7",
                    "caffetine_factor_mean",
                    "nicotine_factor_mean",
                    "family_factor_mean",
                    "napping_factor_mean",
                    "alc_factor_mean")]

subset2 = df[c("sp_freq_coded",
              "age_coded",
              "education_coded",
              "is_female",
              "SC1",
              "SC2",
              "SC3",
              "SC4",
              "SC5",
              "SC6",
              "SC7",
              "caffetine_factor_mean",
              "nicotine_factor_mean",
              "family_factor_mean",
              "napping_factor_mean",
              "alc_factor_mean")]

df_complete_s2 <- df_s[complete.cases(subset_s2), ]
df_complete_ns2 <- df_ns[complete.cases(subset_ns2), ]
df_complete2 <- df[complete.cases(subset2), ]

# Student Sample
# Building the models
m0 <- lm(sp_freq_coded ~ 1, data = df_complete_s2, na.action = NULL)
m1 <- lm(sp_freq_coded ~ age_coded + education_coded + is_female, data = df_complete_s2, na.action = NULL)
m2 <- lm(sp_freq_coded ~ age_coded + education_coded + is_female + SC1 + SC2 + SC3 + SC4 + SC5 + SC6 + SC7, data = df_complete_s2, na.action = NULL)
m3 <- lm(sp_freq_coded ~ age_coded + education_coded + is_female + + SC1 + SC2 + SC3 + SC4 + SC5 + SC6 + SC7 + caffetine_factor_mean + nicotine_factor_mean + alc_factor_mean + napping_factor_mean + family_factor_mean, data = df_complete_s2, na.action = NULL)
# anova comparison
anova(m0)
anova(m0, m1, m2, m3)
anova_results <- anova(m1, m2, m3)
# summary stats
summary(m1)
summary(m2)
summary(m3)

# Non-student Sample
# Building the models
m0 <- lm(sp_freq_coded ~ 1, data = df_complete_ns2, na.action = NULL)
m1 <- lm(sp_freq_coded ~ age_coded + education_coded + is_female, data = df_complete_ns2, na.action = NULL)
m2 <- lm(sp_freq_coded ~ age_coded + education_coded + is_female + SC1 + SC2 + SC3 + SC4 + SC5 + SC6 + SC7, data = df_complete_ns2, na.action = NULL)
m3 <- lm(sp_freq_coded ~ age_coded + education_coded + is_female + SC1 + SC2 + SC3 + SC4 + SC5 + SC6 + SC7 + caffetine_factor_mean + nicotine_factor_mean + alc_factor_mean + napping_factor_mean + family_factor_mean, data = df_complete_ns2, na.action = NULL)
# anova comparison
anova(m0)
anova(m0, m1, m2, m3)
anova_results <- anova(m1, m2, m3)
# summary stats
summary(m1)
summary(m2)
summary(m3)


# Network
library("qgraph")
options(rgl.printRglwidget = TRUE, rgl.useNULL = TRUE)
install.packages("rgl")
library("rgl")
install.packages("bootnet")
library("bootnet")

# Model 1: PSQI+others
subset1  = c("sp_freq_coded",
            "age_coded",
            "education_coded",
            "PSQI",
            "caffetine_factor_mean",
            "nicotine_factor_mean",
            "family_factor_mean",
            "napping_factor_mean",
            "alc_factor_mean")

input_s <- df_complete_s[,subset1]
input_ns <- df_complete_ns[,subset1]
input <- df_complete[,subset1]

# Bootnet threshold
bootnet_thres_s <- estimateNetwork(input_s, 
                                   default = "pcor", 
                                   corMethod= "spearman",
                                   threshold = "sig", 
                                   alpha = 0.05)
bootnet_thres_ns <- estimateNetwork(input_ns, 
                                    default = "pcor", 
                                    corMethod= "spearman",
                                    threshold = "sig", 
                                    alpha = 0.05)
bootnet_thres <- estimateNetwork(input, 
                                 default = "pcor", 
                                 corMethod= "spearman",
                                 threshold = "sig", 
                                 alpha = 0.05)

network_s <- 1*(bootnet_thres_s$graph != 0)
network_ns <- 1*(bootnet_thres_ns$graph != 0)
network <- 1*(bootnet_thres$graph != 0)

m1_bootnet_thres_s <- psychonetrics::ggm(input_s, omega = network_s) %>% runmodel
m1_bootnet_thres_ns <- psychonetrics::ggm(input_ns, omega = network_ns) %>% runmodel
m1_bootnet_thres <- psychonetrics::ggm(input, omega = network) %>% runmodel

# GGM pruning
m1_ggm_prune_s <- ggm(input_s) %>% runmodel %>% prune(alpha=0.05)
m1_ggm_prune_ns <- ggm(input_ns) %>% runmodel %>% prune(alpha=0.05)
m1_ggm_prune <- ggm(input) %>% runmodel %>% prune(alpha=0.05)

# Lasso regulation
lasso_reg_s <- estimateNetwork(input_s, 
                               default = "EBICglasso", 
                               corMethod= "spearman")
lasso_reg_ns <- estimateNetwork(input_ns, 
                                default = "EBICglasso", 
                                corMethod= "spearman")
lasso_reg <- estimateNetwork(input, 
                             default = "EBICglasso", 
                             corMethod= "spearman")

network_s <- 1*(lasso_reg_s$graph != 0)
network_ns <- 1*(lasso_reg_ns$graph != 0)
network <- 1*(lasso_reg$graph != 0)

m1_lasso_reg_s <- psychonetrics::ggm(input_s, omega = network_s) %>% runmodel
m1_lasso_reg_ns <- psychonetrics::ggm(input_ns, omega = network_ns) %>% runmodel
m1_lasso_reg <- psychonetrics::ggm(input, omega = network) %>% runmodel

# ggmModSelect
ggmmodselect_s <- estimateNetwork(input_s, 
                                  default = "ggmModSelect", 
                                  corMethod= "spearman")
ggmmodselect_ns <- estimateNetwork(input_ns, 
                                   default = "ggmModSelect", 
                                   corMethod= "spearman")
ggmmodselect <- estimateNetwork(input, 
                                default = "ggmModSelect", 
                                corMethod= "spearman")

network_s <- 1*(ggmmodselect_s$graph != 0)
network_ns <- 1*(ggmmodselect_ns$graph != 0)
network <- 1*(ggmmodselect$graph != 0)

m1_ggmmodselect_s <- psychonetrics::ggm(input_s, omega = network_s) %>% runmodel
m1_ggmmodselect_ns <- psychonetrics::ggm(input_ns, omega = network_ns) %>% runmodel
m1_ggmmodselect <- psychonetrics::ggm(input, omega = network) %>% runmodel

# Stepup model search
m1_stepup_s <- ggm(input_s) %>% runmodel %>% prune(adjust = "fdr", alpha = 0.01) %>% stepup(criterion="bic", alpha=0.05)
m1_stepup_ns <- ggm(input_ns) %>% runmodel %>% prune(adjust = "fdr", alpha = 0.01) %>% stepup(criterion="bic", alpha=0.05)
m1_stepup <- ggm(input) %>% runmodel %>% prune(adjust = "fdr", alpha = 0.01) %>% stepup(criterion="bic", alpha=0.05)

# Compare all models
compare(m1_bootnet_thres=m1_bootnet_thres, m1_ggm_prune=m1_ggm_prune, m1_lasso_reg = m1_lasso_reg, m1_ggmmodselect=m1_ggmmodselect,m1_stepup=m1_stepup)
compare(m1_bootnet_thres_s=m1_bootnet_thres_s, m1_ggm_prune_s=m1_ggm_prune_s, m1_lasso_reg_s = m1_lasso_reg_s, m1_ggmmodselect_s=m1_ggmmodselect_s,m1_stepup_s=m1_stepup_s)
compare(m1_bootnet_thres_ns=m1_bootnet_thres_ns, m1_ggm_prune_ns=m1_ggm_prune_ns, m1_lasso_reg_ns = m1_lasso_reg_ns, m1_ggmmodselect_ns=m1_ggmmodselect_ns,m1_stepup_ns=m1_stepup_ns)

m1_stepup %>% parameters

# Plot the network
matrix_s <- getmatrix(m1_stepup_s, "omega")
matrix_ns <- getmatrix(m1_stepup_ns, "omega")
matrix <- getmatrix(m1_stepup, "omega")

L <- averageLayout(matrix_s, matrix_ns,matrix)
layout(t(1:3))
qgraph(matrix_s, filetype = "jpg", filename = "m1_stepup_s",layout = L, title  = "m1_stepup_s", theme = "colorblind", cut = 0, nodeNames=subset1)
qgraph(matrix_ns, filetype = "jpg", filename = "m1_stepup_ns",layout = L, title  = "m1_stepup_ns", theme = "colorblind", cut = 0, nodeNames=subset1)
qgraph(matrix, filetype = "jpg", filename = "m1_stepup",layout = L, title  = "m1_stepup", theme = "colorblind", cut = 0, nodeNames=subset1)

# Centrality indices
centralityPlot(matrix_s, include = "all", orderBy = "ExpectedInfluence",labels=subset1)
centralityPlot(matrix_ns, include = "all", orderBy = "ExpectedInfluence",labels=subset1)
centralityPlot(matrix, include = "all", orderBy = "ExpectedInfluence",labels=subset1)

# Edge stability
CIplot(m1_stepup_s, "omega", labels = subset1, labelstart = 0.2)
CIplot(m1_stepup_ns, "omega", labels = subset1, labelstart = 0.2)
CIplot(m1_stepup, "omega", labels = subset1, labelstart = 0.2)

# Model 2: SC1-7+others

subset2  = c("sp_freq_coded",
             "age_coded",
             "education_coded",
             "SC1",
             "SC2",
             "SC3",
             "SC4",
             "SC5",
             "SC6",
             "SC7",
             "caffetine_factor_mean",
             "nicotine_factor_mean",
             "family_factor_mean",
             "napping_factor_mean",
             "alc_factor_mean")

input_s <- df_complete_s[,subset2]
input_ns <- df_complete_ns[,subset2]
input <- df_complete[,subset2]

# Bootnet threshold
bootnet_thres_s <- estimateNetwork(input_s, 
                                   default = "pcor", 
                                   corMethod= "spearman",
                                   threshold = "sig", 
                                   alpha = 0.05)
bootnet_thres_ns <- estimateNetwork(input_ns, 
                                    default = "pcor", 
                                    corMethod= "spearman",
                                    threshold = "sig", 
                                    alpha = 0.05)
bootnet_thres <- estimateNetwork(input, 
                                 default = "pcor", 
                                 corMethod= "spearman",
                                 threshold = "sig", 
                                 alpha = 0.05)

network_s <- 1*(bootnet_thres_s$graph != 0)
network_ns <- 1*(bootnet_thres_ns$graph != 0)
network <- 1*(bootnet_thres$graph != 0)

m2_bootnet_thres_s <- psychonetrics::ggm(input_s, omega = network_s) %>% runmodel
m2_bootnet_thres_ns <- psychonetrics::ggm(input_ns, omega = network_ns) %>% runmodel
m2_bootnet_thres <- psychonetrics::ggm(input, omega = network) %>% runmodel

# GGM pruning
m2_ggm_prune_s <- ggm(input_s) %>% runmodel %>% prune(alpha=0.05)
m2_ggm_prune_ns <- ggm(input_ns) %>% runmodel %>% prune(alpha=0.05)
m2_ggm_prune <- ggm(input) %>% runmodel %>% prune(alpha=0.05)

# Lasso regulation
lasso_reg_s <- estimateNetwork(input_s, 
                               default = "EBICglasso", 
                               corMethod= "spearman")
lasso_reg_ns <- estimateNetwork(input_ns, 
                                default = "EBICglasso", 
                                corMethod= "spearman")
lasso_reg <- estimateNetwork(input, 
                             default = "EBICglasso", 
                             corMethod= "spearman")

network_s <- 1*(lasso_reg_s$graph != 0)
network_ns <- 1*(lasso_reg_ns$graph != 0)
network <- 1*(lasso_reg$graph != 0)

m2_lasso_reg_s <- psychonetrics::ggm(input_s, omega = network_s) %>% runmodel
m2_lasso_reg_ns <- psychonetrics::ggm(input_ns, omega = network_ns) %>% runmodel
m2_lasso_reg <- psychonetrics::ggm(input, omega = network) %>% runmodel

# ggmModSelect
ggmmodselect_s <- estimateNetwork(input_s, 
                                  default = "ggmModSelect", 
                                  corMethod= "spearman")
ggmmodselect_ns <- estimateNetwork(input_ns, 
                                   default = "ggmModSelect", 
                                   corMethod= "spearman")
ggmmodselect <- estimateNetwork(input, 
                                default = "ggmModSelect", 
                                corMethod= "spearman")

network_s <- 1*(ggmmodselect_s$graph != 0)
network_ns <- 1*(ggmmodselect_ns$graph != 0)
network <- 1*(ggmmodselect$graph != 0)

m2_ggmmodselect_s <- psychonetrics::ggm(input_s, omega = network_s) %>% runmodel
m2_ggmmodselect_ns <- psychonetrics::ggm(input_ns, omega = network_ns) %>% runmodel
m2_ggmmodselect <- psychonetrics::ggm(input, omega = network) %>% runmodel

# Stepup model search
m2_stepup_s <- ggm(input_s) %>% runmodel %>% prune(adjust = "fdr", alpha = 0.01) %>% stepup(criterion="bic", alpha=0.05)
m2_stepup_ns <- ggm(input_ns) %>% runmodel %>% prune(adjust = "fdr", alpha = 0.01) %>% stepup(criterion="bic", alpha=0.05)
m2_stepup <- ggm(input) %>% runmodel %>% prune(adjust = "fdr", alpha = 0.01) %>% stepup(criterion="bic", alpha=0.05)

# Compare all models
compare(m2_bootnet_thres=m2_bootnet_thres, m2_ggm_prune=m2_ggm_prune, m2_lasso_reg = m2_lasso_reg, m2_ggmmodselect=m2_ggmmodselect,m2_stepup=m2_stepup)
compare(m2_bootnet_thres_s=m2_bootnet_thres_s, m2_ggm_prune_s=m2_ggm_prune_s, m2_lasso_reg_s = m2_lasso_reg_s, m2_ggmmodselect_s=m2_ggmmodselect_s,m2_stepup_s=m2_stepup_s)
compare(m2_bootnet_thres_ns=m2_bootnet_thres_ns, m2_ggm_prune_ns=m2_ggm_prune_ns, m2_lasso_reg_ns = m2_lasso_reg_ns, m2_ggmmodselect_ns=m2_ggmmodselect_ns,m2_stepup_ns=m2_stepup_ns)

m2_stepup %>% parameters

# Plot the network
matrix_s <- getmatrix(m2_stepup_s, "omega")
matrix_ns <- getmatrix(m2_stepup_ns, "omega")
matrix <- getmatrix(m2_stepup, "omega")

L <- averageLayout(matrix_s, matrix_ns,matrix)
layout(t(1:3))
color = c("Target", rep("Demographic",2), rep("Sleep Quality Items",7), rep("Behavioral Factors",5))
qgraph(matrix_s, filetype = "jpg", filename = "m2_stepup_s",layout = L, title  = "m2_stepup_s", theme = "colorblind", cut = 0, nodeNames=subset2,groups=color)
qgraph(matrix_ns, filetype = "jpg", filename = "m2_stepup_ns",layout = L, title  = "m2_stepup_ns", theme = "colorblind", cut = 0, nodeNames=subset2,groups=color)
qgraph(matrix, filetype = "jpg", filename = "m2_stepup",layout = L, title  = "m2_stepup", theme = "colorblind", cut = 0, nodeNames=subset2,groups=color)

# Centrality indices
centralityPlot(matrix_s, include = "all", orderBy = "ExpectedInfluence",labels=subset2)
centralityPlot(matrix_ns, include = "all", orderBy = "ExpectedInfluence",labels=subset2)
centralityPlot(matrix, include = "all", orderBy = "ExpectedInfluence",labels=subset2)

# Edge stability
CIplot(m2_stepup_s, "omega", labels = subset2, labelstart = 0.2)
CIplot(m2_stepup_ns, "omega", labels = subset2, labelstart = 0.2)
CIplot(m2_stepup, "omega", labels = subset2, labelstart = 0.2)
